language: objective-c
osx_image: xcode8
#xcode_project: <>
xcode_workspace: MSAPIService.xcworkspace
xcode_scheme: MSAPIService
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=MSAPIService
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
